### ISSUE TITLE
pre-trained model is invalid

### ISSUE THREAD

**Issue by Mickeyyyang** [CMinhBui/dd_qnet#1]
hello, May I ask, can pre-trained models be provided? The link you gave is invalid.

**Comment by ghost** [comment]
@xuyangbit I've restored the links, you can found them with the same address:
Env: [https://drive.google.com/open?id=19ldjgpsS303IGfPCBrT-WEf18FYy4quL](https://drive.google.com/open?id=19ldjgpsS303IGfPCBrT-WEf18FYy4quL)
Pretrained model: [https://drive.google.com/open?id=1g8cAxaL6CcqavwaLLHuiR6_4DxYZ_WFq](https://drive.google.com/open?id=1g8cAxaL6CcqavwaLLHuiR6_4DxYZ_WFq)
